apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: dnsstacks.stacks.aws.hops.ops.com.ai
spec:
  compositeTypeRef:
    apiVersion: stacks.aws.hops.ops.com.ai/v1alpha1
    kind: DNSStack
  mode: Pipeline
  pipeline:
  - functionRef:
      name: hops-ops-stack-aws-dnsrender
    step: render
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: crossplane-contrib-function-auto-ready
